# Generated by Django 4.2.3 on 2023-07-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='urgency',
            field=models.CharField(choices=[('Low', 'Low'), ('Mid', 'Mid'), ('High', 'High'), ('GET IT DONE', 'GET IT DONE')], max_length=20),
        ),
    ]
