# Generated by Django 4.2.3 on 2023-07-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_task_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.CharField(choices=[('Just Starting', 'Just Starting'), ('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('Finished', 'Finished')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
